LIVES = 10
ENEMY_DOWN_SCORE = 5
SCORE_FILE = 'scores.txt'
WELCOME_STRING = 'Enter your name: '
GOODBYE_STRING = 'Good bye!'
START_STRING = 'Enter "start" for play or "exit" for exit: '
START_EXIT_KEY_WORDS = {'start': 'START', 'exit': 'EXIT'}
SELECT_STRiNG = 'Select your champion. Enter '
WRONG_SELECT = 'Wrong select. Enter the 1, 2 or 3'
ATTACK_STRING = {-1: "You missed!", 0: "It's a draw!", 1: "You attacked successfully!"}
DEFENSE_STRING = {-1: "You defenced successfully!", 0: "It's a draw!", 1: "You missed!"}
ENEMY_DOWN_STRING = "Enemy falling down! Your score is"
LIVES_STRING = "Your Lives is "
GAME_OVER_STRING = "Game over. Your score is "
